---
title: "Exercises_07"
author: "Kaden Pickering"
date: "3/6/2022"
output: html_document
---

Exercises 3.3.6

Given this UI:
```{r}
ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)
```


Fix the simple errors found in each of the three server functions below. First try spotting the problem just by reading the code; then run the code to make sure you’ve fixed it.

```{r}
server1 <- function(input, output, server) {
  input$greeting <- renderText(paste0("Hello ", name))
}
# The issue with this code is that it says "input$greeting" when it should say "output$greeting". 
```


```{r}
server2 <- function(input, output, server) {
  greeting <- paste0("Hello ", input$name)
  output$greeting <- renderText(greeting)
}

# In this example, there are two lines when one line of code would be sufficient. 
# The code should be: 
server2 <- function(input, output, server) {
   output$greeting <- paste0("Hello ", input$name)
 }
```

```{r}
server3 <- function(input, output, server) {
  output$greting <- paste0("Hello", input$name)
}

# This example is pretty easy to see what's wrong... the greeting is spelled wrong in the code so it won't run 
server3 <- function(input, output, server) {
  output$greeting <- paste0("Hello", input$name)

```


# Question 2: Draw the reactive graph for the following server functions:

```{r}
server1 <- function(input, output, session) {
  c <- reactive(input$a + input$b)
  e <- reactive(c() + input$d)
  output$f <- renderText(e())
}
server2 <- function(input, output, session) {
  x <- reactive(input$x1 + input$x2 + input$x3)
  y <- reactive(input$y1 + input$y2)
  output$z <- renderText(x() / y())
}
server3 <- function(input, output, session) {
  d <- reactive(c() ^ input$d)
  a <- reactive(input$a * 10)
  c <- reactive(b() / input$c) 
  b <- reactive(a() + input$b)
}
```



