---
title: "Mapping"
author: "Kaden Pickering"
date: "2/7/2022"
output: html_document
---

```{r}
library(maps)
library(tidyverse)

state_df <- ggplot2::map_data("state")
state_df
```

```{r}
ggplot(data = state_df,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_map() +
  theme_void()
```


```{r}
library(usdata)
state_stats
```

```{r}
state_stats <- state_stats %>% mutate(state = str_to_lower(state))
state_full <- left_join(state_df, state_stats, by = c("region" = "state"))

ggplot(data = state_full, aes(x = long, y = lat, group = group)) +
  geom_polygon(colour = "black", aes(fill = coal)) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme_void() +
  scale_fill_viridis_b()
```

Exercise 1. 
```{r}
Growth_map <- 
state_full %>%
  as_tibble() %>%
  mutate(growth_rate = 100 * (pop2010 - pop2000) / pop2000)

```

```{r}
ggplot(data = Growth_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(colour = "black", aes(fill = growth_rate)) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme_void() +
  scale_fill_distiller(type = "div", direction = 1)
```
# Exercise 2
## fermenter is for binning continuous
## brewer is for discrete colours
## distiller is for continuous variable

