---
title: "Quiz_06_InClass"
author: "Kaden Pickering"
date: "3/2/2022"
output: html_document
---

# Question 1: Using the SLU Majors data set, give an example of a situation where you would construct a static graph instead of an interactive graph. Why would the static graph be better?

An example of a situation where you would construct a static graph would be if you only wanted the viewer of your visualization to be able to compare, let's say what minor a person take at SLU, if they are a STAT major. This would be the case if you only wanted certain information to be portrayed by the graph to send a certain message. The less information available to a user would lead them to different conclusions about the data and if you wanted to target a certain conclusion or persuade the user to come to a conclusion you want, a static graph would be helpful in getting that message across. 

# Question 2: Consider this version of the Tennis App from class:

```{r}
library(shiny); library(tidyverse)
atp_df <- read_csv("data-2/atp_matches_2019.csv")
wta_df <- read_csv("data-2/wta_matches_2019.csv")
both_df <- bind_rows(atp_df, wta_df)

both_long <- both_df %>% pivot_longer(c(winner_name, loser_name))

## only keep players who have player over 50 matches
both_n50 <- both_long %>% group_by(value) %>% count() %>%
  filter(n > 50)

## construct various statistics
major_tennis <- semi_join(both_long, both_n50, by = c("value"))
major_tennis <- major_tennis %>% mutate(w_svperc = 100 * w_1stIn / w_svpt,
                        l_svperc = 100 * l_1stIn / l_svpt,
                        w_firstwon = 100 * w_1stWon / w_1stIn,
                        l_firstwon = 100 * l_1stWon / l_1stIn,
                        w_secondwon = 100 * w_2ndWon / (w_svpt - w_1stIn),
                        l_secondwon = 100 * l_2ndWon / (l_svpt - l_1stIn))

major_tennis_w <- major_tennis %>% filter(name == "winner_name")
major_tennis_l <- major_tennis %>% filter(name == "loser_name")

w_small <- major_tennis_w %>% select(value, winner_seed, w_ace, w_df, w_svperc,
                                     w_firstwon, w_secondwon) %>%
  rename(seed = winner_seed, ace = w_ace, df = w_df, svperc = w_svperc,
         firstwon = w_firstwon, secondwon = w_secondwon)

l_small <- major_tennis_l %>% select(value, loser_seed, l_ace, l_df, l_svperc, l_firstwon, l_secondwon)  %>%
  rename(seed = loser_seed, ace = l_ace, df = l_df, svperc = l_svperc,
         firstwon = l_firstwon, secondwon = l_secondwon)

df <- bind_rows(w_small, l_small) %>%
  rename(player = "value")
df



var_choices <- names(df)[3:7]

library(shiny)

df_static <- reactive ({ 
  df_new<- wta_df %>% filter(statistic == input$statistic) })
  
  
ui <- fluidPage(
  sidebarLayout(sidebarPanel(
    selectizeInput("playerchoice",
                   label = "Choose a Player", choices = levels(factor(df$player)),
                   selected = "Aryna Sabalenka"),
    radioButtons("varchoice", label = "Choose a Statistic",
                 choices = var_choices)),
    mainPanel(plotOutput("histgraph"))
  )
)

server <- function(input, output, session) {
  
  df_sub <- reactive({
    df %>% filter(player == input$playerchoice)
  })
  
  
  hist_plot <- reactive({
    # ggplot(df_sub(), aes_string(x = input$varchoice)) +
    # geom_histogram(colour = "black", fill = "white", bins = 15)
    ggplot(df_sub(), aes(x = .data[[input$varchoice]])) +
      geom_histogram(colour = "black", fill = "white", bins = 15)
  })
  
  output$histgraph <- renderPlot({
    hist_plot()
  })
  
  output$table <- renderPlot({
    ggplot(data = df, aes(x = playerchoice, y = statistic )) +
    geom_boxplot()
  })
}

shinyApp(ui, server)
```

# Add a plot below the histogram that is a side-by-side boxplot for comparing a serving statistic of two players. The user should be able to select the two players as well as the statistic being compared.


